name: app_aprendizaje
description: "App educativa de matemáticas con IA"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_messaging: ^16.0.3      
  flutter_local_notifications: ^19.4.2 
  firebase_core: ^4.2.0          
  firebase_auth: ^6.1.1          
  cloud_firestore: ^6.0.3        

  image_picker: ^1.1.2
  pdf: ^3.11.0
  printing: ^5.13.4
  syncfusion_flutter_charts: ^31.1.19
  fl_chart: ^1.1.0
  uuid: ^4.5.1
  intl: ^0.20.2
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.1
  # -----------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#2196F3"  
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/icon.png