// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOlllEyPD-a-kGuUQPNhMUwNB07FMwArQ',
    appId: '1:76010994155:web:31a2f9b5c7dbe49c4c41ae',
    messagingSenderId: '76010994155',
    projectId: 'mathlearningapp-e2d05',
    authDomain: 'mathlearningapp-e2d05.firebaseapp.com',
    storageBucket: 'mathlearningapp-e2d05.firebasestorage.app',
    measurementId: 'G-V57J3RRTF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7H8Vine20qJgoWab2LAR17xMpwJtyX7s',
    appId: '1:76010994155:android:7cda184c5f03f8124c41ae',
    messagingSenderId: '76010994155',
    projectId: 'mathlearningapp-e2d05',
    storageBucket: 'mathlearningapp-e2d05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA187oQD-l7cnQ6-Zi15SNORD1wToatVvU',
    appId: '1:76010994155:ios:059c75dfed48e5e14c41ae',
    messagingSenderId: '76010994155',
    projectId: 'mathlearningapp-e2d05',
    storageBucket: 'mathlearningapp-e2d05.firebasestorage.app',
    iosBundleId: 'com.example.appAprendizaje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA187oQD-l7cnQ6-Zi15SNORD1wToatVvU',
    appId: '1:76010994155:ios:059c75dfed48e5e14c41ae',
    messagingSenderId: '76010994155',
    projectId: 'mathlearningapp-e2d05',
    storageBucket: 'mathlearningapp-e2d05.firebasestorage.app',
    iosBundleId: 'com.example.appAprendizaje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOlllEyPD-a-kGuUQPNhMUwNB07FMwArQ',
    appId: '1:76010994155:web:9bfe3f3de0b9b5e14c41ae',
    messagingSenderId: '76010994155',
    projectId: 'mathlearningapp-e2d05',
    authDomain: 'mathlearningapp-e2d05.firebaseapp.com',
    storageBucket: 'mathlearningapp-e2d05.firebasestorage.app',
    measurementId: 'G-45BFG79TZ6',
  );
}
